grafana:
  enabled: true
  adminPassword: admin

  host: grafana.local.gd
  service:
    port: 80
    targetPort: 3000
    portName: "grafana-local"

  ingress:
    enabled: true
    hosts:
      - grafana.local.gd

  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
    # alerts:
    #   enabled: true
    #   label: argocd.argoproj.io/instance
    #   folder: /etc/grafana/provisioning/alerting
    #   regex: "^grafana-alerts\\.yaml$" 
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
      isDefaultDatasource: false

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Mimir
          type: prometheus
          uid: lgtm-mimir
          url: http://mimir-gateway.mimir.svc.cluster.local:8080/prometheus
          editable: true
          isDefault: true
          orgId: 1
          jsonData:
            httpHeaderName1: "X-Scope-OrgID"
          secureJsonData:
            httpHeaderValue1: "lgtm-kind"
        - name: Loki
          type: loki
          uid: "lgtm-loki"
          url: http://loki-gateway.loki.svc.cluster.local
          editable: true
          orgId: 1
          jsonData:
            httpHeaderName1: "X-Scope-OrgId"
          secureJsonData:
            httpHeaderValue1: "lgtm-kind"
        - name: Tempo
          type: tempo
          url: http://tempo.tempo.svc.cluster.local:16686
          editable: true
          orgId: 1
          uid: "lgtm-tempo"
          jsonData:
            httpHeaderName1: X-Scope-OrgId
            tracesToLogsV2:
              datasourceUid: "lgtm-loki"
              spanStartTimeShift: 1h
              spanEndTimeShift: -1h
              tags:
                - job
                - instance
                - pod
                - namespace
              filterByTraceID: 'False'
              filterBySpanID: 'False'
              customQuery: 'True'
              query: method='${__span.tags.method}'
            tracesToMetrics:
              datasourceUid: "lgtm-mimir"
              spanStartTimeShift: 1h
              spanEndTimeShift: -1h
              tags:
                - key: service.name
                  value: service
                - key: job
              queries:
                - name: Sample query
                  query: sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))
            serviceMap:
              datasourceUid: "lgtm-mimir"
            nodeGraph:
              enabled: 'True'
            search:
              hide: 'False'
            lokiSearch:
              datasourceUid: "lgtm-loki"
            traceQuery:
              timeShiftEnabled: 'True'
              spanStartTimeShift: 1h
              spanEndTimeShift: -1h
            spanBar:
              type: Tag
              tag: http.path
          secureJsonData:
            httpHeaderValue1: "lgtm-kind"

  # extraVolumes:
  #   - name: grafana-alerts
  #     configMap:
  #       name: grafana-alerts

  nodeSelector:
    ingress-ready: "true"  # ✅ Ensure your nodes can schedule the pod

  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"  # ✅ Allows scheduling on control plane if needed

  resources:
    requests:
      cpu: 100m
      memory: 128Mi

  alerting:
    rules.yaml:
      apiVersion: 1
      groups:
          - orgId: 1
            name: Cluster-Health
            folder: system-observability
            interval: 1m
            rules:
              - uid: eepapp6ldo4xsc
                title: CRITICAL Disk Space Usage
                condition: C
                data:
                  - refId: A
                    relativeTimeRange:
                      from: 600
                      to: 0
                    datasourceUid: lgtm-mimir
                    model:
                      editorMode: code
                      expr: (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"}) * 100
                      instant: true
                      intervalMs: 1000
                      legendFormat: __auto
                      maxDataPoints: 43200
                      range: false
                      refId: A
                  - refId: C
                    relativeTimeRange:
                      from: 600
                      to: 0
                    datasourceUid: __expr__
                    model:
                      conditions:
                          - evaluator:
                              params:
                                  - 90
                                  - 100
                              type: within_range
                            operator:
                              type: and
                            query:
                              params:
                                  - C
                            reducer:
                              params: []
                              type: last
                            type: query
                      datasource:
                          type: __expr__
                          uid: __expr__
                      expression: A
                      intervalMs: 1000
                      maxDataPoints: 43200
                      refId: C
                      type: threshold
                noDataState: NoData
                execErrState: Error
                for: 1m
                annotations:
                  description: ""
                  runbook_url: ""
                  summary: ""
                labels:
                  severity: CRITICAL
                isPaused: false
                notification_settings:
                  receiver: Edge Alert Webhook

              - uid: eepapp6ldo4xsd
                title: CRITICAL CPU Utilization Per Node
                condition: C
                data:
                  - refId: A
                    relativeTimeRange:
                      from: 600
                      to: 0
                    datasourceUid: lgtm-mimir
                    model:
                      editorMode: code
                      expr: 100 - (avg(rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)
                      instant: true
                      intervalMs: 1000
                      legendFormat: __auto
                      maxDataPoints : 43200
                      range: false
                      refId: A
                  - refId: C
                    relativeTimeRange:
                      from: 600
                      to: 0
                    datasourceUid: __expr__
                    model:
                      conditions:
                          - evaluator:
                              params:
                                  - 90
                                  - 100
                              type: within_range
                            operator:
                              type: and
                            query:
                              params:
                                  - C
                            reducer:
                              params: []
                              type: last
                            type: query
                      datasource:
                          type: __expr__
                          uid: __expr__
                      expression: A
                      intervalMs: 1000
                      maxDataPoints: 43200
                      refId: C
                      type: threshold
                noDataState: NoData
                execErrState: Error
                for: 1m
                annotations:
                  description: ""
                  runbook_url: ""
                  summary: ""
                labels:
                  severity: CRITICAL
                isPaused: false
                notification_settings:
                  receiver: Edge Alert Webhook        
              
              - uid: eepapp6ldo4xse
                title: CRITICAL Memory Usage (Including Cache)
                condition: C
                data:
                  - refId: A
                    relativeTimeRange:
                      from: 600
                      to: 0
                    datasourceUid: lgtm-mimir
                    model:
                      editorMode: code
                      expr: ((node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes) * 100
                      instant: true
                      intervalMs: 1000
                      legendFormat: __auto
                      maxDataPoints : 43200
                      range: false
                      refId: A
                  - refId: C
                    relativeTimeRange:
                      from: 600
                      to: 0
                    datasourceUid: __expr__
                    model:
                      conditions:
                          - evaluator:
                              params:
                                  - 90
                                  - 100
                              type: within_range
                            operator:
                              type: and
                            query:
                              params:
                                  - C
                            reducer:
                              params: []
                              type: last
                            type: query
                      datasource:
                          type: __expr__
                          uid: __expr__
                      expression: A
                      intervalMs: 1000
                      maxDataPoints: 43200
                      refId: C
                      type: threshold
                noDataState: NoData
                execErrState: Error
                for: 1m
                annotations:
                  description: ""
                  runbook_url: ""
                  summary: ""
                labels:
                  severity: CRITICAL
                isPaused: false
                notification_settings:
                  receiver: Edge Alert Webhook

              - uid: eepapp6ldo4xsf
                title: CRITICAL CrashLoopBackOff Detection
                condition: C
                data:
                  - refId: A
                    relativeTimeRange:
                      from: 600
                      to: 0
                    datasourceUid: lgtm-mimir
                    model:
                      editorMode: code
                      expr: count(kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff"})
                      instant: true
                      intervalMs: 1000
                      legendFormat: __auto
                      maxDataPoints : 43200
                      range: false
                      refId: A
                  - refId: C
                    relativeTimeRange:
                      from: 600
                      to: 0
                    datasourceUid: __expr__
                    model:
                      conditions:
                          - evaluator:
                              params:
                                  - 0
                              type: gt
                            operator:
                              type: and
                            query:
                              params:
                                  - C
                            reducer:
                              params: []
                              type: last
                            type: query
                      datasource:
                          type: __expr__
                          uid: __expr__
                      expression: A
                      intervalMs: 1000
                      maxDataPoints: 43200
                      refId: C
                      type: threshold
                noDataState: NoData
                execErrState: Error
                for: 1m
                annotations:
                  description: ""
                  runbook_url: ""
                  summary: ""
                labels:
                  severity: CRITICAL
                isPaused: false
                notification_settings:
                  receiver: Edge Alert Webhook

              - uid: eepapp6ldo4xsf
                title: WARNING Disk Space Usage
                condition: C
                data:
                  - refId: A
                    relativeTimeRange:
                      from: 600
                      to: 0
                    datasourceUid: lgtm-mimir
                    model:
                      editorMode: code
                      expr: (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"}) * 100
                      instant: true
                      intervalMs: 1000
                      legendFormat: __auto
                      maxDataPoints: 43200
                      range: false
                      refId: A
                  - refId: C
                    relativeTimeRange:
                      from: 600
                      to: 0
                    datasourceUid: __expr__
                    model:
                      conditions:
                          - evaluator:
                              params:
                                  - 80
                                  - 91
                              type: within_range
                            operator:
                              type: and
                            query:
                              params:
                                  - C
                            reducer:
                              params: []
                              type: last
                            type: query
                      datasource:
                          type: __expr__
                          uid: __expr__
                      expression: A
                      intervalMs: 1000
                      maxDataPoints: 43200
                      refId: C
                      type: threshold
                  
                noDataState: NoData
                execErrState: Error
                for: 1m
                annotations:
                  description: ""
                  runbook_url: ""
                  summary: ""
                labels:
                  severity: WARNING
                isPaused: false
                notification_settings:
                  receiver: Edge Alert Webhook

              - uid: eepapp6ldo4xsg
                title: WARNING CPU Utilization Per Node
                condition: C
                data:
                  - refId: A
                    relativeTimeRange:
                      from: 600
                      to: 0
                    datasourceUid: lgtm-mimir
                    model:
                      editorMode: code
                      expr: 100 - (avg(rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)
                      instant: true
                      intervalMs: 1000
                      legendFormat: __auto
                      maxDataPoints : 43200
                      range: false
                      refId: A
                  - refId: C
                    relativeTimeRange:
                      from: 600
                      to: 0
                    datasourceUid: __expr__
                    model:
                      conditions:
                          - evaluator:
                              params:
                                  - 80
                                  - 91
                              type: within_range
                            operator:
                              type: and
                            query:
                              params:
                                  - C
                            reducer:
                              params: []
                              type: last
                            type: query
                      datasource:
                          type: __expr__
                          uid: __expr__
                      expression: A
                      intervalMs: 1000
                      maxDataPoints: 43200
                      refId: C
                      type: threshold
                  
                noDataState: NoData
                execErrState: Error
                for: 1m
                annotations:
                  description: ""
                  runbook_url: ""
                  summary: ""
                labels:
                  severity: WARNING
                isPaused: false
                notification_settings:
                  receiver: Edge Alert Webhook        
              
              - uid: eepapp6ldo4xsh
                title: WARNING Memory Usage (Including Cache)
                condition: C
                data:
                  - refId: A
                    relativeTimeRange:
                      from: 600
                      to: 0
                    datasourceUid: lgtm-mimir
                    model:
                      editorMode: code
                      expr: ((node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes) * 100
                      instant: true
                      intervalMs: 1000
                      legendFormat: __auto
                      maxDataPoints : 43200
                      range: false
                      refId: A
                  - refId: C
                    relativeTimeRange:
                      from: 600
                      to: 0
                    datasourceUid: __expr__
                    model:
                      conditions:
                          - evaluator:
                              params:
                                  - 80
                                  - 91
                              type: within_range
                            operator:
                              type: and
                            query:
                              params:
                                  - C
                            reducer:
                              params: []
                              type: last
                            type: query
                      datasource:
                          type: __expr__
                          uid: __expr__
                      expression: A
                      intervalMs: 1000
                      maxDataPoints: 43200
                      refId: C
                      type: threshold
                  
                noDataState: NoData
                execErrState: Error
                for: 1m
                annotations:
                  description: ""
                  runbook_url: ""
                  summary: ""
                labels:
                  severity: WARNING
                isPaused: false
                notification_settings:
                  receiver: Edge Alert Webhook

    contactpoints.yaml:
      apiVersion: 1
      contactPoints:
        - orgId: 1
          name: Edge Alert Webhook
          receivers:
            - uid: eep5pp60s1ybkd
              type: webhook
              settings:
                url: https://webhook.site/9422a43a-323f-47d3-a617-e2f329910885  #will be changed
                httpMethod: POST
                customHeaders: {}
                template: alert_template
              disableResolveMessage: false